apiVersion: apps/v1
kind: Deployment
metadata:
  name: huskerly-message-deployment
  namespace: huskerly
  labels:
    app: huskerly-message
spec:
  replicas: 3
  selector:
    matchLabels:
      app: huskerly-message
  template:
    metadata:
      labels:
        app: huskerly-message
    spec:
      containers:
        - name: huskerly-message
          image: message-image
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: huskerly-message-lb
  namespace: huskerly
  labels:
    app: huskerly-message
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
spec:
  type: LoadBalancer
  selector:
    app: huskerly-message
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
