apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base

images:
  - name: user-image
    newName: USER_IMAGE_REPO
    newTag: IMAGE_TAG
  - name: message-image
    newName: MESSAGE_IMAGE_REPO
    newTag: IMAGE_TAG
  - name: upload-image
    newName: UPLOAD_IMAGE_REPO
    newTag: IMAGE_TAG
