apiVersion: v1
kind: ServiceAccount
metadata:
  name: huskerly-sa-upload
  namespace: huskerly
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::058264409130:role/huskerly-role-upload
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: huskerly-upload-deployment
  namespace: huskerly
  labels:
    app: huskerly-upload
spec:
  replicas: 3
  selector:
    matchLabels:
      app: huskerly-upload
  template:
    metadata:
      labels:
        app: huskerly-upload
    spec:
      serviceAccountName: huskerly-sa-upload
      containers:
        - name: huskerly-upload
          image: upload-image
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: huskerly-upload-lb
  namespace: huskerly
  labels:
    app: huskerly-upload
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: huskerly-upload
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
