apiVersion: v1
kind: Service
metadata:
  name: huskerly-user-public-lb
  namespace: huskerly
  labels:
    app: huskerly-user
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: huskerly-user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: huskerly-user-private-lb
  namespace: huskerly
  labels:
    app: huskerly-user
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
spec:
  type: LoadBalancer
  selector:
    app: huskerly-user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
