apiVersion: v1
kind: ServiceAccount
metadata:
  name: huskerly-sa-user
  namespace: huskerly
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::058264409130:role/huskerly-role-user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: huskerly-user-deployment
  namespace: huskerly
  labels:
    app: huskerly-user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: huskerly-user
  template:
    metadata:
      labels:
        app: huskerly-user
    spec:
      serviceAccountName: huskerly-sa-user
      containers:
        - name: huskerly-user
          image: user-image
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: huskerly-user-lb
  namespace: huskerly
  labels:
    app: huskerly-user
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
spec:
  type: LoadBalancer
  selector:
    app: huskerly-user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
