name: Deploy microservice to EKS

on:
  workflow_call:
    inputs:
      service:
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Repo
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: "Install terraform"
        uses: hashicorp/setup-terraform@v3

      - name: Install kustomize
        run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::058264409130:role/github-role
          aws-region: us-east-2
          role-session-name: github-oidc-session

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Connect to EKS cluster
        run: aws eks update-kubeconfig --name huskerly-cluster --region us-east-2

      - name: Relay terraform state file outputs
        id: terraform
        run: |
          cd terraform/network
          terraform init
          echo "repo-arn=$(terraform output -raw ${{ inputs.service }}-repo-arn)" >> "$GITHUB_OUTPUT"
          cd ../..

      - name: Kustomize deployment with latest tag
        run: |
          cd k8s/${{ inputs.service }}
          sed -i "s|IMAGE_REPO|${{ steps.terraform.outputs.repo-arn }}|g" kustomization.yaml
          sed -i "s|IMAGE_TAG|${{ github.sha }}|g" kustomization.yaml
          cd ../..
        # (debug command) kubectl get nodes -v=10

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        run: |
          cd services/${{ inputs.service }}
          IMAGE=${{ steps.terraform.outputs.repo-arn }}:${{ github.sha }}
          docker build -t ${IMAGE} .
          docker push ${IMAGE}
          cd ../..

      - name: Deploy to EKS
        run: kubectl apply -k k8s/${{ inputs.service }}

permissions:
  id-token: write
  contents: read
