name: Deploy message microservice to EKS

on:
  push:
    paths:
      - "services/message/**"
  workflow_dispatch:

jobs:
  deploy-message-service:
    uses: ./.github/workflows/deploy.yaml
    with:
      service: message
    permissions:
      id-token: write
      contents: read
