name: Deploy upload microservice to EKS

on:
  push:
    paths:
      - "services/upload/**"
  workflow_dispatch:

jobs:
  deploy-upload-service:
    uses: ./.github/workflows/deploy.yaml
    with:
      service: upload
    permissions:
      id-token: write
      contents: read
