name: Deploy user microservice to EKS

on:
  push:
    paths:
      - "services/user/**"
  workflow_dispatch:

jobs:
  deploy-user-service:
    uses: ./.github/workflows/deploy.yaml
    with:
      service: user
    permissions:
      id-token: write
      contents: read
