name: Deploy user microservice to EKS

on:
  push:
    branches:
      - "main"

jobs:
  deploy-user:
    uses: ./.github/workflows/deploy.yaml
    with:
      service: user
    permissions:
      id-token: write
      contents: read
