name: Deploy user microservice to EKS

on:
  push:
    paths:
      - "services/upload"

jobs:
  deploy-user:
    uses: ./.github/workflows/deploy.yaml
    with:
      service: user
    permissions:
      id-token: write
      contents: read
